stages:
  build_meta:
    cmd: python pracds_final/data/build_meta.py data/raw/metadata.csv
    deps:
    - pracds_final/data/build_meta.py
    params:
    - build.meta.queries
    outs:
    - data/raw/metadata.csv
  build_filter:
    cmd: python pracds_final/data/build_filter.py data/raw/metadata.csv data/raw/filter_ids.json
    deps:
    - data/raw/metadata.csv
    - pracds_final/data/build_filter.py
    params:
    - build.filter.total_seconds
    - build.filter.unique_birds
    outs:
    - data/raw/filter_ids.json
