stages:
  build_meta:
    cmd: python pracds_final/data/build_meta.py data/raw/metadata.csv
    deps:
    - pracds_final/data/build_meta.py
    params:
    - build.meta.queries
    outs:
    - data/raw/metadata.csv
  build_filter:
    cmd: python pracds_final/data/build_filter.py data/raw/metadata.csv data/raw/filter_ids.json
    deps:
    - data/raw/metadata.csv
    - pracds_final/data/build_filter.py
    params:
    - build.filter.total_seconds
    - build.filter.unique_birds
    outs:
    - data/raw/filter_ids.json
  build_audio:
    cmd: python pracds_final/data/build_audio.py data/raw/metadata.csv data/raw/filter_ids.json
      data/raw/recordings
    deps:
    - data/raw/filter_ids.json
    - data/raw/metadata.csv
    - pracds_final/data/build_audio.py
    outs:
    - data/raw/recordings
  build_sono:
    cmd: python pracds_final/data/build_sono.py data/raw/metadata.csv data/raw/filter_ids.json
      data/raw/sonograms
    deps:
    - data/raw/filter_ids.json
    - data/raw/metadata.csv
    - pracds_final/data/build_sono.py
    outs:
    - data/raw/sonograms
  build_song_vs_call:
    cmd: python pracds_final/data/build_song_vs_call.py data/raw/metadata.csv data/raw/filter_ids.json
      data/raw/song_vs_call.json
    deps:
      - data/raw/filter_ids.json
      - data/raw/metadata.csv
      - pracds_final/data/build_song_vs_call.py
    outs:
      - data/raw/song_vs_call.json
  proc_svc_split:
    cmd: python pracds_final/features/proc_svc_split.py data/raw/song_vs_call.json data/processed/svc_split.json
    deps:
      - data/raw/song_vs_call.json
      - pracds_final/features/proc_svc_split.py
    outs:
      - data/processed/svc_split.json
  proc_audio:
    cmd: python pracds_final/features/proc_audio.py data/raw/song_vs_call.json data/raw/recordings data/processed/audio_timeseries.json
    deps:
      - data/raw/song_vs_call.json
      - data/raw/recordings
      - pracds_final/features/proc_audio.py
    outs:
      - data/processed/audio_features.json
